let myJokes = [
    {
        category: "Programming",
        type: "single",
        joke: "Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 37,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: "The glass is neither half-full nor half-empty, the glass is twice as big as it needs to be.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 23,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: "I have a joke about Stack Overflow, but you would say it's a duplicate.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        safe: true,
        id: 301,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: "The generation of random numbers is too important to be left to chance.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 39,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: 'Judge: "I sentence you to the maximum punishment..."\nMe (thinking): "Please be death, please be death..."\nJudge: "Learn Java!"\nMe: "Damn."',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 45,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: 'A SQL statement walks into a bar and sees two tables.\nIt approaches, and asks "may I join you?"',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 5,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: 'A man is smoking a cigarette and blowing smoke rings into the air. His girlfriend becomes irritated with the smoke and says "Can\'t you see the warning on the cigarette pack? Smoking is hazardous to your health!" to which the man replies, "I am a programmer.  We don\'t worry about warnings; we only worry about errors."',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 38,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: 'Today I learned that changing random stuff until your program works is "hacky" and a "bad coding practice" but if you do it fast enough it\'s "Machine Learning" and pays 4x your current salary.',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 33,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: '"Knock, knock."\n"Who\'s there?"\n\n[very long pause]\n\n"Java."',
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 36,
        safe: true,
        lang: "en",
    },
    {
        category: "Programming",
        type: "single",
        joke: "Java is like Alzheimer's, it starts off slow, but eventually, your memory is gone.",
        flags: {
            nsfw: false,
            religious: false,
            political: false,
            racist: false,
            sexist: false,
            explicit: false,
        },
        id: 27,
        safe: false,
        lang: "en",
    },
];

let index =  Math.floor(Math.random() * (myJokes.length -1))
console.log(index)
joke.innerHTML = myJokes[index].joke